Html first task1
ok-technopolis-2020/Gromov_Maxim pull request #1
Opened 2020-10-08 21:32 UTC by Maxim-byte

2020-10-09 12:11 UTC, fromanywhere requested changes

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +   <input name="textfield" type="text" value="What needs to be done?"></p>
а откуда абзац?

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +  <input type="checkbox" name="HTML" checked>
форматирование конечно хочет внимания. Отступы там

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +  <button><span aria-hidden="true">&times;</span></button></p>
а почему aria-hidden?

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +  <button><span aria-hidden="true">&times;</span></button></p>
А зачем вложенный span?

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +    <div class="css-block">
нуу, наверное нет смысла делать имена классов привязанными к их контенту

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +  <button name="all-button" type="submit"> All</button>
здесь будет фильтр из радиокнопок

2020-10-09 12:11 UTC, fromanywhere commented on index.html
> +   <button>√</button>
aria

2020-10-09 13:38 UTC, Maxim-byte commented on index.html
> +    <div class="css-block">
+

2020-10-09 13:38 UTC, Maxim-byte commented on index.html
> +  <button><span aria-hidden="true">&times;</span></button></p>
+

2020-10-09 13:38 UTC, Maxim-byte commented on index.html
> +  <input type="checkbox" name="HTML" checked>
+

2020-10-09 13:38 UTC, Maxim-byte commented on index.html
> +   <input name="textfield" type="text" value="What needs to be done?"></p>
+

2020-10-09 13:38 UTC, Maxim-byte commented on index.html
> +   <button>√</button>
+

2020-10-09 13:46 UTC, Maxim-byte commented on index.html
> +  <button name="all-button" type="submit"> All</button>
Можно пожалуйста более подробно, не совсем понятно(

2020-10-12 09:16 UTC, fromanywhere requested changes

2020-10-12 09:16 UTC, fromanywhere commented on index.html
> +        <section class="main-controls__second-item">
Идея описывать классы на элементы списка не очень. Их же сколько угодно может быть

2020-10-12 09:16 UTC, fromanywhere commented on index.html
> +    	    <button>&times</button></p>
aria

2020-10-12 09:16 UTC, fromanywhere commented on index.html
> +        <label class="task-filter__item">
Здесь все табы лучше обернуть дополнительно еще одним узлом

2020-10-12 12:17 UTC, Maxim-byte commented on index.html
> +        <section class="main-controls__second-item">
+

2020-10-12 12:17 UTC, Maxim-byte commented on index.html
> +    	    <button>&times</button></p>
+

2020-10-12 12:17 UTC, Maxim-byte commented on index.html
> +        <label class="task-filter__item">
+

2020-10-12 12:17 UTC, Maxim-byte commented
@fromanywhere

2020-10-13 08:05 UTC, fromanywhere approved these changes

2020-10-13 08:05 UTC, fromanywhere commented on index.html
> +  			<button name="clear-button" type="submit" aria-label="clear completed tasks">Clear completed</button>
Насчет type="submit" спорно

2020-10-13 09:41 UTC, merged